name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'

      - name: Test
        run: |
          go test -v ./...

      - name: Build
        run: |
          go build -o app ./cmd/server/main.go

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'sa-east-1'
          role-to-assume: 'arn:aws:iam::472772625577:oidc-provider/token.actions.githubusercontent.com'


      - name: Login to AWS
        run: |
          aws sts get-caller-identity
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "AWS_REGION: $AWS_REGION"

      - name: Build and push Docker image
        run: |
          docker build -t clube-do-churrasco .
          docker tag clube-do-churrasco:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.sa-east-1.amazonaws.com/clube-do-churrasco:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.sa-east-1.amazonaws.com/clube-do-churrasco:latest