name: Build and Deploy

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'

      - name: Test
        run: |
          go test -v ./...

      - name: Build
        run: |
          go build -o app ./cmd/server/main.go

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'sa-east-1'
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          docker build -t facilitandotecnologia/clube-do-churrasco-api .
          docker tag facilitandotecnologia/clube-do-churrasco-api:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.sa-east-1.amazonaws.com/facilitandotecnologia/clube-do-churrasco-api:latest 
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.sa-east-1.amazonaws.com/facilitandotecnologia/clube-do-churrasco-api:latest